name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm clean-install
    - name: build
      id: build
      run: npm run build
    - run: npm run lint
    - name: Compress action step
      id: tarball
      run: tar czf tableaunoir-master.tar.gz --transform s,^dist/,tableaunoir/, dist
      if: ${{ always() && steps.build.outcome == 'success' }}
    - name: upload tableaunoir bundle
      if: ${{ always() && steps.tarball.outcome == 'success' }}
      uses: actions/upload-artifact@v2
      with:
        name: tableaunoir current version
        path: tableaunoir-master.tar.gz
